### ISSUE TITLE
[Feature] , load process and definition extensions before load activity extensions .

### ISSUE THREAD

**Issue by saeedtabrizi** [paed01/bpmn-elements#10]
There is `loadExtention` method and works well for loading activity extensions .
But there is no way to load Process Extensions before loading activity extensions .
I recommend to have a  `loadProcessExtensions` in process the following code in the custom extensions : 
`
 <bpmn:process id="Process_103i680" name="Team Choosing Process" isExecutable="true" nowjs:candidateStarterGroups="Admins,Publishers" nowjs:candidateStarterUsers="Saeed,Hamid" nowjs:versionTag="1">
    <bpmn:extensionElements>
      <nowjs:executionListener event="start">
        <nowjs:script scriptFormat="javascript">function(t,i){
  console.log("Hello Start Execution Process");
}</nowjs:script>
      </nowjs:executionListener>
      <nowjs:executionListener event="end">
        <nowjs:script scriptFormat="javascript">function(t,i){
  console.log("Hello End Execution Process");
}</nowjs:script>
      </nowjs:executionListener>
    </bpmn:extensionElements>
`
Thanks

**Comment by paed01** [comment]
Something like this 7f78583?

**Comment by saeedtabrizi** [comment]
Hi @paed01 
Many thanks for rapid & good action to my request and implement the requested feature in the shortest possible time and i'm excited. 
I want to be contributor of  **bpmn-engine** and **bpmn-element** project if you accept it.
Currently i'm working on a bpms project that dependent to this project exactly that you can find it here https://github.com/nowcando/nowjs-bpms.

Regards
Saeed Tabrizi
