### ISSUE TITLE
Exception When connecting a message intermediate throw event to a empty process 

### ISSUE THREAD

**Issue by simonhoss** [paed01/bpmn-elements#14]
**Exception**
`TypeError: Cannot read property 'find' of undefined`

![diagram](https://user-images.githubusercontent.com/1117667/67664579-31448580-f968-11e9-9a6e-e0e40506cb88.png)

**Comment by paed01** [comment]
I patched the exception but the lane is not executed by default, since it has no elements.

**Comment by paed01** [comment]
@simonhoss any outstanding issues described in this issue?
