### ISSUE TITLE
Gateway Asynchronous Execution

### ISSUE THREAD

**Issue by denny99** [paed01/bpmn-elements#16]
The basic javascript implementation of your bpmn-engine expects a callback function to be passed, so we can write async JS Functions. But your are not using this kind of callback everywhere.

For example the Gateway Implementation:

```
  if (flow.evaluateCondition(executeMessage, onEvaluateError)) {
        conditionMet = true;
        outbound.push({id: flow.id, action: 'take'});
      } else {
        if (evaluateError) return broker.publish('execution', 'execute.error', cloneContent(content, {error: evaluateError}));
        outbound.push({id: flow.id, action: 'discard'});
      }
```

Here we can never use async functions at all. The callback just sets the error object and that's it.

The script tasks utilizes it correclty:

```
 return script.execute(ExecutionScope(activity, executeMessage), scriptCallback);

    function scriptCallback(err, output) {
```

Right now i've extended the Gateways to check if the condition is a promise and then awaits the result.

So is this behaviour intended? And I have to extend all classes with promise awaiting?

**Comment by paed01** [comment]
I guess my idea was that all information about the decision is present when outbound flows evaluate condition. This can be achieved by extensions using [formatting](/paed01/bpmn-elements/blob/master/docs/Extension.md). I have added tests for my claims here fb698e2.

Though, I agree it's somewhat inconsistent. Feel free to PR a suggestion of how it should work.

**Comment by denny99** [comment]
Alright. Right now we are still working on the fundamentals of our architecture but i guess, in a month or so, i can start adding PR for things we've implemented. And you can decide if it should be a core feature :)

Another thing that we need is the Camunda take Action Script. I think this is not implemented?

**Comment by paed01** [comment]
Regarding camunda elements have a look at https://github.com/paed01/bpmn-engine/issues/100

**Comment by paed01** [comment]
I will start working on this issue as well. Tried to explain the difference in script execution behaviour to a friend and realised that I was just rambling. The change is kind of breaking so I guess it should be toggled somehow...

**Comment by paed01** [comment]
@denny99 I have updated both the engine and this project with asynchronous execution of sequence flow script conditions. Can you have a look if it meets your needs?

**Comment by denny99** [comment]
Should be fine. Somewhat like node express

**Comment by paed01** [comment]
Can we close this issue until another reveals itself?
