### ISSUE TITLE
Is this plugin enough for state machine?

### ISSUE THREAD

**Issue by kyoz** [paed01/bpmn-elements#18]
Hello @paed01 , thank you very much for your awesome work on this and other library for bpmn.

Since bpmn seem doesn't support for client-side web app, i don't have any other choice than using this library.

My use case is:

I want to define a work flow with bpmn.js and base on it result to perform different action for use. One by one

Example:

![image](https://user-images.githubusercontent.com/29815830/110418731-9cf54180-80ca-11eb-8827-45eca30815d3.png)

I'v tried this lib a little bit. It run well. But i don't know how to make it run one by one, stop as condition and wait for user interact, and then base on user interact result, i'll do some action then jump to other step...

Can this library handle that and what do i need to pay attention to?

Thank you in advanced :heart:

**Comment by kyoz** [comment]
Seem serviceTask & Gateway is what i want. :smile: 

```
    const options = {
      Logger: this.Logger,
      services: {
        taskOne(arg, next) {
          console.log('[Task 1] Start');
          console.log('[Task 1] Waiting');

          const result = prompt("[Task 1] Input", "");

          console.log('[Task 1] Done: ', {result});

          next();
        },
        taskTwo(arg, next) {
          console.log('[Task 2] Start');
          console.log('[Task 2] Waiting');

          const result = prompt("[Task 2] Input", "");

          console.log('[Task 2] Done: ', {result});

          next();
        },
        taskThree(arg, next) {
          console.log('Task THREE');
          next();
        },
        isOk(arg, next) {
          next();
        },
        chooseAction(arg, next) {
          next();
        }
      },
    };
```

**Comment by paed01** [comment]
Sorry for the late reply. So, if I understand correctly, you solved the issue your self?

**Comment by kyoz** [comment]
Haha, i almost forgot this.

Yes i'v solve it and everything working perfectly for my work.

Thank you very much 😋
