### ISSUE TITLE
When the implementation field of a serviceTask includes a string with comma symbols inside, it split the string

### ISSUE THREAD

**Issue by javierlopezaircall** [paed01/bpmn-elements#19]
In getPropertyValue.js file, line 54:

```

if (args) {
      callArguments = callArguments.concat(args.split(','));
      callArguments = callArguments.map(argument => {
        return getFunctionArgument(base, argument.trim(), fnScope);
      });
} else {
      callArguments.push(base);
}

```

If args is of the form "'This is a string, with a comma inside'", the split() method will split it into two wrong arguments.

To avoid this you should use a function that handles the string arguments in a different way than the rest of the arguments. It can be done with a stack, or a very smart regexp, but a simple implementation could be something like this:

```
function splitArguments(args, base){
    let insideString = false;
    let argCompleted = false;
    let arg = '';

    let callArguments = [];

    for(let i=0;i<args.length;i++){
      let charPos = args.charAt(i);
      if(!insideString && charPos === ',') {
        argCompleted = true;
      }
      else{
        arg += charPos;

        if (charPos === '\'') {

          if(insideString){
            argCompleted = true;
          }
          else{
            insideString = true;
          }
        }
      }

      if(argCompleted){
        callArguments.push(getFunctionArgument(base, arg.trim(),fnScope));
        arg = '';
        insideString = false;
        argCompleted = false;
      }
    }

    if(arg.trim() != ''){
      callArguments.push(getFunctionArgument(base, arg.trim(),fnScope));
    }

    return callArguments;
  }

function executeFn(fn, args, base) {
    if (!fn) return;
    let callArguments = [];

    if (args) {

      callArguments = splitArguments(args, base);
      // callArguments = callArguments.concat(args.split(','));
      // callArguments = callArguments.map(argument => {
      //   return getFunctionArgument(base, argument.trim(), fnScope);
      // });
    } else {
      callArguments.push(base);
    }

    if (!fnScope) return fn.apply(null, callArguments);
    return function ScopedIIFE() {
      // eslint-disable-line no-extra-parens
      return fn.apply(this, callArguments);
    }.call(fnScope);
  }
```

**Comment by paed01** [comment]
I know the expression parser is not perfect. My plan is to refactor it to a proper compiler with lexer, tokenizer, etc. Happy times.

Until then you can pass your own expression handler as an option. The interface is described in [Expression](../blob/master/docs/Expression.md).

**Comment by javierlopezaircall** [comment]
Thanks for your response!! Really you're doing a very good job with the bpmn engine... B-)

I think that for us to build a complete expression handler only to fix an issue on the executeFn() function of getPropertyValue.js is a little bit like to use a sledgehammer to crack nuts, but if you don't mind we could collaborate with you: we could develop a simple fix and then create a PR for your review.

 Thanks in any case!

**Comment by paed01** [comment]
That would be great. I’m happy to accept tested PRs.
