### ISSUE TITLE
exception resuming SequenceFlow discard - timing of engine save?

### ISSUE THREAD

**Issue by jonklein** [paed01/bpmn-elements#2]
I'm seeing an occasional exception when resuming the engine on a user form task.  The exception is coming from the processing of a postponed sequence flow discard message.  What's odd to me is that the sequence flow in question is not anywhere near the task being resumed - this flow is at the end of the process, while the execution task is in the middle.

```
action: "discard"
id: "SequenceFlow_1fys6qm"
isDefault: true
isSequenceFlow: true
parent: {id: "Process_1n2nxgh", type: "bpmn:Process", executionId: "Process_1n2nxgh_320ae9a2"}
sequenceId: "SequenceFlow_1fys6qm_280a0a09"
sourceId: "Task_0i7bvta"
state: "pre-flight"
targetId: "EndEvent_1d0yx81"
type: "bpmn:SequenceFlow"
```

Partial stacktrace: 
```
< (node:75899) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'resume' of undefined
<     at postponed.slice.forEach (/Users/jk/Development/bpmn/node_modules/bpmn-elements/dist/src/process/ProcessExecution.js:151:38)
<     at Array.forEach (<anonymous>)
<     at resume (/Users/jk/Development/bpmn/node_modules/bpmn-elements/dist/src/process/ProcessExecution.js:149:23)
```

In debugging, I found that I could resolve the issue by introducing a small delay in saving the engine state: when saving the engine on either `flow.discard` or `activity.wait`, the flow discard event is processed *after*.  If I delay until that message is processed, the save/resume works correctly.

So two issues, I guess:

1) It seems like the engine is not handling these messages correctly on resume, if my reading of the code is correct.

2) When is the "correct" time to save engine state?  Is this happening because I'm incorrectly saving the engine with messages left in the queue?

**Comment by paed01** [comment]
1. I think there is a null guard missing. But the question is why it is needed? I'll start digging.

### 2.
The ambition is that a resumable state should be available at all times. Though, it has proven hard to implement.

I try to save state at activity-level, i.e. when the activity is started or waiting, etc, and not when the process is in a transition.

Saving state is rather costly, lots of objects to iterate over and asking for state. To top it of, the smqp module uses JSON stringify and parse (my fault).

**Comment by paed01** [comment]
Should we consider this resolved with the merge?

**Comment by jonklein** [comment]
Yes, I'll close this out.

I'm still curious why the discarded flow is sticking around when the engine is saved in activity.wait and whether that's a sign of another issue.  The test in #8 demonstrates that scenario if the defensive check is removed.

**Comment by paed01** [comment]
True that. Needs further investigation.

**Comment by paed01** [comment]
I managed to figure out why this happens - it's the sequence flow pre-flight message that is still in queue waiting for confirmation. Your guard handles that, and I guess it's necessary. Sequence flows has no need to be resumed.

**Comment by paed01** [comment]
I have refactored handling of outbound sequence flows so this issue might be resolved.

**Comment by paed01** [comment]
No more pre-flight messages able to linger since [v2](/paed01/bpmn-elements/blob/master/CHANGELOG.md#200).
