### ISSUE TITLE
Expected attribute loopCounter for StandardLoopCharacteristics

### ISSUE THREAD

**Issue by Ichigo85** [paed01/bpmn-elements#27]
I am trying to use bpmn-engine on a simple example, like this bpmn I just uploaded.

[loopSimple.txt](https://github.com/paed01/bpmn-elements/files/8004658/loopSimple.txt)

As described in [BPMN 2.0 specifics](https://www.omg.org/spec/BPMN/2.0.1/PDF), there should be an attribute loopCounter used at runtime to count the number of loops. I tried to use it on the bpmn but it does not work.

Is it possible to implement it, according to the specifics? Else, what variable should I use for the loopCounter?

Thank you very much.

**Comment by paed01** [comment]
That has been named `index` (0-based) in the engine. Since the aim is to be BPMN2 compliant, I will add it in a future release. Thank you for making me aware.

**Comment by Ichigo85** [comment]
Hello! I thought it already was BPMN 2.0 compliant, do you have a roadmap or a list of what's missing?

**Comment by paed01** [comment]
IMHO the project has BPMN2.0 core support. But 100% [BPMN2.0](https://www.omg.org/spec/BPMN/2.0.1/PDF) is hard to reach, especially since I'm doing this on my limited free time. Feel free to contribute if you are missing something.

**Comment by Ichigo85** [comment]
I will gladly contribute, thank you. In fact, I was thinking to fork your project, but I have probably one question before starting. I have seen that also making a valid expression like
`${content.index} < 10`

does not work, because the expression is correctly resolved (0 < 10) but not evaluated. Since I am still not deeply into the mechanisms of bpmn-engine I prefer to ask. Would it be better to add a "evaluateExpression" that calculate the final result, using it only for loopCharacteristics, or can I edit the "resolveExpression" function to implement this behaviour?
Or am I missing something?

**Comment by paed01** [comment]
The builtin expression parser is basic RegEx and rather stupid. It's mainly there for reference.

You can configure your own expression handler in [`enviroment.expressions`](/[paed01/bpmn-elements/blob/master/docs/Environment.md]/paed01/bpmn-elements/blob/master/docs/Definition.md) or use the excellent community expression handler by [aircall](https://www.npmjs.com/package/@aircall/expression-parser) (#23)

**Comment by paed01** [comment]
Can I close this issue or do we require the property to exist?

**Comment by Ichigo85** [comment]
Hi! Yes, I'll close the issue myself. Thank you for your help!
