### ISSUE TITLE
Async ExpressionHandler

### ISSUE THREAD

**Issue by Florian79** [paed01/bpmn-elements#39]
Hello!
apparently I can extend the behaviour of an activity - but how to extend the behaviour of a SequenceFlow?

I try to use an ExpressionHandler with an asynchronous resolveExpression function, which is not allowed in the interface but could be solved easily by overwriting the [ExpressionCondition.prototype.execute](https://github.com/paed01/bpmn-elements/blob/6ad9bbbe3885535ee7e6ed788d1636f3905f452b/src/flows/SequenceFlow.js#L193) method as follows:

```
ExpressionCondition.prototype.execute = function execute(message, callback) {
const owner = this._owner;
   try {
    const result = owner.environment.resolveExpression(this.expression, owner.createMessage(message));
    return Promise.resolve(result).then(r =>
        callback ? callback(null, r) : result).catch(err =>
        callback ? callback(err) : err)
    //if (callback) return callback(null, result);
    //return result;
  } catch (err) {
    if (callback) return callback(err);
    throw err;
  }
};
```

or is there any other mechanism to deal with an async ExpressionHandler?

Thank you!
Florian

**Comment by paed01** [comment]
Since  Expression- and ScriptCondition are not exposed in the api (at the moment), I would extend the `SequenceFlow.prototype.getCondition` function or make your own extended SequenceFlow.

```js
import * as elements from 'bpmn-elements';

class FlorianSequenceFlow extends elements.SequenceFlow {
  getCondition() {
    const condition = super.getCondition();
    if (condition?.type !== 'expression') return condition;

    const execute = condition.execute;
    condition.execute = asyncExecute.bind(condition);

    return condition;

    function asyncExecute(message, callback) {
      execute.call(condition, message, (executeErr, result) => {
        if (executeErr) return callback(executeErr);
        return Promise.resolve(result).then(r =>
          callback ? callback(null, r) : result).catch(err =>
          callback ? callback(err) : err);
      });
    }
  }
}
```

**Comment by paed01** [comment]
Can I close this issue or are you still struggling?
